CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  display_name text CHECK (display_name IS NULL OR char_length(display_name) BETWEEN 1 AND 80),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "People can view their profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "People can create their profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "People can update their profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "People can delete their profile" ON public.profiles FOR DELETE TO authenticated USING (auth.uid() = id);
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL CHECK (char_length(text) BETWEEN 10 AND 500),
  category text NOT NULL CHECK (category IN ('infancia','adolescencia','adulto','curiosa')),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.questions TO authenticated;
GRANT ALL ON public.questions TO service_role;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in people can read active questions" ON public.questions FOR SELECT TO authenticated USING (active = true);

CREATE TABLE public.answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  question_id bigint NOT NULL REFERENCES public.questions(id) ON DELETE RESTRICT,
  answer_text text NOT NULL CHECK (char_length(trim(answer_text)) >= 10),
  assigned_date date NOT NULL DEFAULT current_date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, assigned_date)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.answers TO authenticated;
GRANT ALL ON public.answers TO service_role;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "People can view their answers" ON public.answers FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "People can create their answers" ON public.answers FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can update their answers" ON public.answers FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can delete their answers" ON public.answers FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TRIGGER answers_updated_at BEFORE UPDATE ON public.answers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE INDEX answers_user_date_idx ON public.answers (user_id, assigned_date DESC);

CREATE TABLE public.answer_analysis (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id bigint NOT NULL UNIQUE REFERENCES public.answers(id) ON DELETE CASCADE,
  people text[] NOT NULL DEFAULT '{}',
  emotions text[] NOT NULL DEFAULT '{}',
  lesson text,
  is_milestone boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.answer_analysis TO authenticated;
GRANT ALL ON public.answer_analysis TO service_role;
ALTER TABLE public.answer_analysis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "People can view analysis of their answers" ON public.answer_analysis FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.answers a WHERE a.id = answer_id AND a.user_id = auth.uid()));
CREATE POLICY "People can create analysis of their answers" ON public.answer_analysis FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.answers a WHERE a.id = answer_id AND a.user_id = auth.uid()));
CREATE POLICY "People can update analysis of their answers" ON public.answer_analysis FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.answers a WHERE a.id = answer_id AND a.user_id = auth.uid())) WITH CHECK (EXISTS (SELECT 1 FROM public.answers a WHERE a.id = answer_id AND a.user_id = auth.uid()));
CREATE POLICY "People can delete analysis of their answers" ON public.answer_analysis FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.answers a WHERE a.id = answer_id AND a.user_id = auth.uid()));
CREATE TRIGGER answer_analysis_updated_at BEFORE UPDATE ON public.answer_analysis FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.recurring_topics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  topic_name text NOT NULL CHECK (char_length(topic_name) BETWEEN 1 AND 120),
  frequency integer NOT NULL CHECK (frequency >= 3),
  last_mentioned date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, topic_name)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recurring_topics TO authenticated;
GRANT ALL ON public.recurring_topics TO service_role;
ALTER TABLE public.recurring_topics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "People can view their topics" ON public.recurring_topics FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "People can create their topics" ON public.recurring_topics FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can update their topics" ON public.recurring_topics FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can delete their topics" ON public.recurring_topics FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TRIGGER recurring_topics_updated_at BEFORE UPDATE ON public.recurring_topics FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.generated_writing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  writing_type text NOT NULL CHECK (writing_type IN ('chapter','biography')),
  category text CHECK (category IS NULL OR category IN ('infancia','adolescencia','adulto','curiosa')),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 160),
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.generated_writing TO authenticated;
GRANT ALL ON public.generated_writing TO service_role;
ALTER TABLE public.generated_writing ENABLE ROW LEVEL SECURITY;
CREATE POLICY "People can view their generated writing" ON public.generated_writing FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "People can create their generated writing" ON public.generated_writing FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can update their generated writing" ON public.generated_writing FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "People can delete their generated writing" ON public.generated_writing FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TRIGGER generated_writing_updated_at BEFORE UPDATE ON public.generated_writing FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.questions (text, category) VALUES
('What is the earliest place you remember calling home?', 'infancia'),
('Which childhood smell instantly takes you back?', 'infancia'),
('Who made you feel safest when you were young, and how?', 'infancia'),
('What game could hold your attention for hours?', 'infancia'),
('What family ritual shaped your earliest years?', 'infancia'),
('Describe a childhood day you wish you could revisit.', 'infancia'),
('What did you believe about the world that now makes you smile?', 'infancia'),
('Which teacher first recognized something special in you?', 'infancia'),
('What was your favorite hiding place?', 'infancia'),
('When did you first feel truly brave?', 'infancia'),
('What friendship defined your teenage years?', 'adolescencia'),
('Which song became the soundtrack to your adolescence?', 'adolescencia'),
('When did you first challenge an adult’s point of view?', 'adolescencia'),
('What did you dream your future would look like?', 'adolescencia'),
('Describe a moment when you felt you finally belonged.', 'adolescencia'),
('What mistake from adolescence taught you the most?', 'adolescencia'),
('Who influenced your sense of style or identity?', 'adolescencia'),
('What was your first taste of independence?', 'adolescencia'),
('Which fear did you quietly carry as a teenager?', 'adolescencia'),
('What advice would you give your sixteen-year-old self?', 'adolescencia'),
('Which decision most changed the direction of your adult life?', 'adulto'),
('What work are you proudest to have done?', 'adulto'),
('How has your definition of success changed?', 'adulto'),
('Who has taught you the most about love?', 'adulto'),
('What difficult season revealed your strength?', 'adulto'),
('Which ordinary routine now feels precious?', 'adulto'),
('What boundary improved your life?', 'adulto'),
('When have you surprised yourself as an adult?', 'adulto'),
('What have you learned about forgiveness?', 'adulto'),
('What legacy do you hope to leave in the people you love?', 'adulto'),
('If your life had a recurring symbol, what would it be?', 'curiosa'),
('Which object would you place in a museum of your life?', 'curiosa'),
('What conversation would you like to hear again word for word?', 'curiosa'),
('If one year of your life were a film, which year would you choose?', 'curiosa'),
('What small coincidence changed something important?', 'curiosa'),
('Which place have you never visited but somehow miss?', 'curiosa'),
('What personal rule do you happily break?', 'curiosa'),
('Which three sounds belong in the story of your life?', 'curiosa'),
('What question have you never been asked but wish someone would ask?', 'curiosa'),
('If tomorrow brought a fresh chapter, what would its title be?', 'curiosa');